server:
  port: 8181
  servlet:
    context-path: /bootcamp
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: alterar_01
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generatede-ddl: false
    hibernate:
      ddl-auto: none

application:
  description: "Projeto criado para o BootCamp DIO e Santander."
  version: "1.2"
